/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Dashboard2RouteImport } from './routes/dashboard2'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated/strategies'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMarketsRouteImport } from './routes/_authenticated/markets'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBotRulesRouteImport } from './routes/_authenticated/bot-rules'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivateRouteImport } from './routes/_authenticated/activate'
import { Route as ApiPublicOnrampWebhookRouteImport } from './routes/api/public/onramp.webhook'
import { Route as ApiPublicHooksBotTickRouteImport } from './routes/api/public/hooks/bot-tick'

const Dashboard2Route = Dashboard2RouteImport.update({
  id: '/dashboard2',
  path: '/dashboard2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketsRoute = AuthenticatedMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotRulesRoute = AuthenticatedBotRulesRouteImport.update({
  id: '/bot-rules',
  path: '/bot-rules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivateRoute = AuthenticatedActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicOnrampWebhookRoute = ApiPublicOnrampWebhookRouteImport.update({
  id: '/api/public/onramp/webhook',
  path: '/api/public/onramp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBotTickRoute = ApiPublicHooksBotTickRouteImport.update({
  id: '/api/public/hooks/bot-tick',
  path: '/api/public/hooks/bot-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard2': typeof Dashboard2Route
  '/activate': typeof AuthenticatedActivateRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bot-rules': typeof AuthenticatedBotRulesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/hooks/bot-tick': typeof ApiPublicHooksBotTickRoute
  '/api/public/onramp/webhook': typeof ApiPublicOnrampWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard2': typeof Dashboard2Route
  '/activate': typeof AuthenticatedActivateRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bot-rules': typeof AuthenticatedBotRulesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/hooks/bot-tick': typeof ApiPublicHooksBotTickRoute
  '/api/public/onramp/webhook': typeof ApiPublicOnrampWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard2': typeof Dashboard2Route
  '/_authenticated/activate': typeof AuthenticatedActivateRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bot-rules': typeof AuthenticatedBotRulesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/markets': typeof AuthenticatedMarketsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/hooks/bot-tick': typeof ApiPublicHooksBotTickRoute
  '/api/public/onramp/webhook': typeof ApiPublicOnrampWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard2'
    | '/activate'
    | '/admin'
    | '/bot-rules'
    | '/dashboard'
    | '/deposit'
    | '/documents'
    | '/markets'
    | '/notifications'
    | '/onboarding'
    | '/portfolio'
    | '/risk'
    | '/settings'
    | '/strategies'
    | '/support'
    | '/transactions'
    | '/welcome'
    | '/withdraw'
    | '/auth/callback'
    | '/api/public/hooks/bot-tick'
    | '/api/public/onramp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard2'
    | '/activate'
    | '/admin'
    | '/bot-rules'
    | '/dashboard'
    | '/deposit'
    | '/documents'
    | '/markets'
    | '/notifications'
    | '/onboarding'
    | '/portfolio'
    | '/risk'
    | '/settings'
    | '/strategies'
    | '/support'
    | '/transactions'
    | '/welcome'
    | '/withdraw'
    | '/auth/callback'
    | '/api/public/hooks/bot-tick'
    | '/api/public/onramp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dashboard2'
    | '/_authenticated/activate'
    | '/_authenticated/admin'
    | '/_authenticated/bot-rules'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposit'
    | '/_authenticated/documents'
    | '/_authenticated/markets'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/portfolio'
    | '/_authenticated/risk'
    | '/_authenticated/settings'
    | '/_authenticated/strategies'
    | '/_authenticated/support'
    | '/_authenticated/transactions'
    | '/_authenticated/welcome'
    | '/_authenticated/withdraw'
    | '/auth/callback'
    | '/api/public/hooks/bot-tick'
    | '/api/public/onramp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  Dashboard2Route: typeof Dashboard2Route
  ApiPublicHooksBotTickRoute: typeof ApiPublicHooksBotTickRoute
  ApiPublicOnrampWebhookRoute: typeof ApiPublicOnrampWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard2': {
      id: '/dashboard2'
      path: '/dashboard2'
      fullPath: '/dashboard2'
      preLoaderRoute: typeof Dashboard2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/markets': {
      id: '/_authenticated/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AuthenticatedMarketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot-rules': {
      id: '/_authenticated/bot-rules'
      path: '/bot-rules'
      fullPath: '/bot-rules'
      preLoaderRoute: typeof AuthenticatedBotRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activate': {
      id: '/_authenticated/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof AuthenticatedActivateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/onramp/webhook': {
      id: '/api/public/onramp/webhook'
      path: '/api/public/onramp/webhook'
      fullPath: '/api/public/onramp/webhook'
      preLoaderRoute: typeof ApiPublicOnrampWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bot-tick': {
      id: '/api/public/hooks/bot-tick'
      path: '/api/public/hooks/bot-tick'
      fullPath: '/api/public/hooks/bot-tick'
      preLoaderRoute: typeof ApiPublicHooksBotTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivateRoute: typeof AuthenticatedActivateRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBotRulesRoute: typeof AuthenticatedBotRulesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedMarketsRoute: typeof AuthenticatedMarketsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivateRoute: AuthenticatedActivateRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBotRulesRoute: AuthenticatedBotRulesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedMarketsRoute: AuthenticatedMarketsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  Dashboard2Route: Dashboard2Route,
  ApiPublicHooksBotTickRoute: ApiPublicHooksBotTickRoute,
  ApiPublicOnrampWebhookRoute: ApiPublicOnrampWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
